project_id = "txdnzzijeqiyvkbozwbx"

[functions.ai-chat]
verify_jwt = false

[functions.tts-eleven]
verify_jwt = false

[functions.stt-transcribe]
verify_jwt = false

[functions.ai-scheduler]
verify_jwt = true

