// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txdnzzijeqiyvkbozwbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZG56emlqZXFpeXZrYm96d2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mzc5NTcsImV4cCI6MjA3MDQxMzk1N30.mv3le69AoTje0WFeJ1LoXVyO2Kcm1UE_L5H6lXA_5s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});